export const MAIN_ROUTE = `/`
export const ADMIN_ROUTE = `/admin`
export const LOGIN_ROUTE = `/login`
export const REGISTRATION_ROUTE = `/registration`
export const CONTACTS = `/contacts`
export const SETTINGS_ROUTE = '/settings'
export const PROGECTS = '/progects'
export const CONFIGURATOR = '/CONFIGURATOR'
export const LOGIN_FORM = '/loginform'
export const USER_CABINET = '/usercabinet'
export const ADMIN_CABINET = '/admincabinet'
export const serverApi = 'http://157.230.98.164'
// export const serverApi = 'http://localhost'
export const botToken = '6305018186:AAHT-wH-K0UtMHBB1_Ki3UW2Z4PC6Y02l8k'
export const chatId = '444452344'
